const topics = [
 ['math','easy','What is 7 × 8?',['48','54','56','64'],2], ['math','easy','What is 15 + 27?',['32','42','52','38'],1], ['math','easy','What is 100 ÷ 4?',['20','25','40','50'],1], ['math','medium','What is the square root of 144?',['10','11','12','14'],2], ['math','medium','What is 3/4 as a percentage?',['25%','50%','75%','80%'],2], ['math','medium','What is 9²?',['18','72','81','99'],2], ['math','easy','How many degrees are in a right angle?',['45','90','180','360'],1], ['math','medium','What is 2⁵?',['10','16','25','32'],3], ['math','easy','What is 1,000 - 375?',['525','625','675','725'],1], ['math','medium','A triangle has angles 60° and 70°. What is the third?',['40°','50°','60°','70°'],1],
 ['geography','easy','What is the capital of France?',['Paris','Rome','Madrid','Berlin'],0], ['geography','easy','Which is the largest ocean?',['Atlantic','Indian','Arctic','Pacific'],3], ['geography','easy','Which country is shaped like a boot?',['Greece','Italy','Chile','Portugal'],1], ['geography','medium','What is the capital of Japan?',['Kyoto','Seoul','Tokyo','Osaka'],2], ['geography','easy','The Nile flows through which continent?',['Asia','Africa','Europe','South America'],1], ['geography','medium','Which is the smallest continent?',['Europe','Australia','Antarctica','Africa'],1], ['geography','easy','Mount Everest is in which mountain range?',['Alps','Andes','Himalayas','Rockies'],2], ['geography','medium','Which country has the most people?',['India','Brazil','China','USA'],0], ['geography','easy','What is the capital of Romania?',['Sofia','Bucharest','Budapest','Belgrade'],1], ['geography','medium','Which desert is in northern Africa?',['Gobi','Sahara','Mojave','Atacama'],1],
 ['science','easy','What planet is known as the Red Planet?',['Venus','Mars','Jupiter','Mercury'],1], ['science','easy','What gas do humans need to breathe?',['Oxygen','Hydrogen','Helium','Carbon dioxide'],0], ['science','easy','How many legs does an insect have?',['4','6','8','10'],1], ['science','medium','What is H₂O commonly called?',['Salt','Oxygen','Water','Hydrogen'],2], ['science','medium','What force pulls objects toward Earth?',['Friction','Magnetism','Gravity','Pressure'],2], ['science','easy','What part of a plant absorbs water?',['Flower','Root','Leaf','Stem'],1], ['science','medium','What is the center of an atom called?',['Electron','Nucleus','Cell','Orbit'],1], ['science','easy','Which animal is a mammal?',['Frog','Shark','Dolphin','Eagle'],2], ['science','medium','At what temperature does water freeze in Celsius?',['0','10','32','100'],0], ['science','medium','What organ pumps blood?',['Liver','Lung','Heart','Kidney'],2],
 ['general','easy','How many days are in a leap year?',['364','365','366','367'],2], ['general','easy','Who wrote Romeo and Juliet?',['Dickens','Shakespeare','Austen','Twain'],1], ['general','easy','Which instrument has black and white keys?',['Guitar','Violin','Piano','Flute'],2], ['general','medium','How many colors are in a rainbow traditionally?',['5','6','7','8'],2], ['general','easy','What is the fastest land animal?',['Lion','Cheetah','Horse','Falcon'],1], ['general','medium','Which language has the most native speakers?',['English','Spanish','Mandarin','Arabic'],2], ['general','easy','How many sides does a hexagon have?',['5','6','7','8'],1], ['general','medium','What is the currency of the United Kingdom?',['Euro','Dollar','Pound','Franc'],2], ['general','easy','Which sport uses a racket and shuttlecock?',['Tennis','Badminton','Squash','Hockey'],1], ['general','medium','How many continents are there?',['5','6','7','8'],2],
 ['language','easy','What is the opposite of “ancient”?',['Old','Modern','Historic','Early'],1], ['language','easy','Which word is a noun?',['Quickly','Blue','Happiness','Run'],2], ['language','medium','What is a synonym for “brave”?',['Timid','Clever','Courageous','Quiet'],2], ['language','easy','What is the plural of “child”?',['Childs','Childes','Children','Childrens'],2], ['language','medium','Which word is spelled correctly?',['Necessary','Necesary','Neccessary','Nessasary'],0], ['language','easy','What punctuation ends a question?',['Period','Comma','Question mark','Colon'],2], ['language','medium','What is the past tense of “go”?',['Goed','Gone','Went','Going'],2], ['language','easy','Which is a vowel?',['B','C','E','G'],2], ['language','medium','What does “predict” mean?',['To guess beforehand','To remember','To explain','To measure'],0], ['language','easy','Which word means “very big”?',['Tiny','Enormous','Narrow','Brief'],1]
];
const extras = [
 ['What is 5 × 6?',['11','25','30','35'],2],['What is 81 ÷ 9?',['7','8','9','10'],2],['How many minutes are in an hour?',['30','45','60','90'],2],['What is 10% of 50?',['5','10','15','20'],0],['Which is a prime number?',['9','12','17','21'],2],['What is 2 + 2 × 3?',['12','10','8','6'],2],['How many meters are in a kilometer?',['100','500','1000','10000'],2],['What is half of 90?',['35','40','45','50'],2],['How many sides has a square?',['3','4','5','6'],1],['What is 12 × 12?',['124','144','154','164'],1],
 ['What is the capital of Spain?',['Lisbon','Madrid','Barcelona','Seville'],1],['Which country is famous for the pyramids at Giza?',['Egypt','Mexico','Greece','Peru'],0],['What is the longest river in South America?',['Amazon','Danube','Yangtze','Mississippi'],0],['Which country is known as the Land of the Rising Sun?',['China','Japan','Thailand','Korea'],1],['What is the capital of Germany?',['Vienna','Berlin','Prague','Warsaw'],1],['Which sea separates Europe and Africa?',['Red Sea','Baltic Sea','Mediterranean Sea','Black Sea'],2],['Which city is nicknamed the Big Apple?',['Los Angeles','Chicago','New York','Boston'],2],['What is the largest country by area?',['Canada','Russia','China','USA'],1],['Which continent is Brazil in?',['Africa','Asia','Europe','South America'],3],['The Danube flows through which continent?',['Europe','Asia','Africa','Australia'],0],
 ['Which star is closest to Earth?',['Sirius','The Sun','Polaris','Vega'],1],['What do bees make?',['Milk','Honey','Silk','Wax only'],1],['What is the hardest natural substance?',['Iron','Diamond','Quartz','Steel'],1],['How many bones are in a typical adult human body?',['106','206','306','406'],1],['Which sense uses the nose?',['Sight','Taste','Smell','Touch'],2],['What is photosynthesis?',['Plant food-making','Animal sleep','Rock formation','Water cycle'],0],['Which blood cells fight infection?',['Red','White','Platelets','Plasma'],1],['What is the closest planet to the Sun?',['Earth','Venus','Mercury','Mars'],2],['What is a baby frog called?',['Cub','Tadpole','Calf','Chick'],1],['Which material is attracted to magnets?',['Wood','Plastic','Iron','Glass'],2],
 ['How many players are on a soccer team on the field?',['9','10','11','12'],2],['Which country invented pizza in its modern form?',['France','Italy','USA','Greece'],1],['How many rings are on the Olympic flag?',['4','5','6','7'],1],['What is the primary color not among these?',['Red','Green','Blue','Purple'],3],['Which month has 28 days in a normal year?',['January','February','March','All of them'],1],['What is a group of stars forming a pattern called?',['Galaxy','Constellation','Orbit','Cluster'],1],['Which animal is known for changing color?',['Chameleon','Penguin','Elephant','Rabbit'],0],['What is the tallest animal?',['Giraffe','Elephant','Horse','Camel'],0],['How many hours are in a day?',['12','24','48','60'],1],['Which game uses kings and queens?',['Checkers','Chess','Golf','Cricket'],1],
 ['What is the comparative of “good”?',['Gooder','Best','Better','More good'],2],['Which word is an adjective?',['Happily','Blue','Jump','Friendship'],1],['What is the first letter of the alphabet?',['A','B','C','Z'],0],['Which is a complete sentence?',['Running fast','The cat sleeps.','Because it rained','Very blue'],1],['What does “tiny” mean?',['Very small','Very loud','Very old','Very fast'],0],['Which word rhymes with “day”?',['Dog','Play','Book','Sun'],1],['What is the opposite of “early”?',['Soon','Late','Fast','First'],1],['Which word is a verb?',['Jump','Green','Chair','Quiet'],0],['What is a dictionary used for?',['Cooking','Word meanings','Weather','Maps'],1],['Which mark shows possession?',["Apostrophe",'Comma','Dash','Bracket'],0]
];
let id = 1; const questions = topics.map(x => ({ id:String(id++), category:x[0], difficulty:x[1], prompt:x[2], options:x[3], correctIndex:x[4] }));
extras.forEach((x,i) => questions.push({ id:String(id++), category:['math','geography','science','general','language'][i%5], difficulty:i%3?'medium':'easy', prompt:x[0], options:x[1], correctIndex:x[2] }));
function nextQuestion(room) { const used=room.usedQuestions || new Set(); let pool=questions.filter(q=>!used.has(q.id)); if(!pool.length){used.clear(); pool=questions;} const q=pool[Math.floor(Math.random()*pool.length)]; used.add(q.id); room.usedQuestions=used; return q; }
module.exports = { questions, nextQuestion };
